// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pod.Core.Infrastructure;

namespace Pod.Core.Migrations
{
    [DbContext(typeof(PodContext))]
    [Migration("20210124060312_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Pod.Core.Domain.PaymentRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardHolder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PaymentStateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("RequestId");

                    b.HasIndex("PaymentStateId")
                        .IsUnique();

                    b.ToTable("PaymentRequest");
                });

            modelBuilder.Entity("Pod.Core.Domain.PaymentStates", b =>
                {
                    b.Property<Guid>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaymentRequestRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.HasKey("PaymentStatusId");

                    b.HasIndex("PaymentRequestRequestId");

                    b.ToTable("PaymentStates");
                });

            modelBuilder.Entity("Pod.Core.Domain.PaymentRequest", b =>
                {
                    b.HasOne("Pod.Core.Domain.PaymentStates", "PaymentState")
                        .WithOne()
                        .HasForeignKey("Pod.Core.Domain.PaymentRequest", "PaymentStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentState");
                });

            modelBuilder.Entity("Pod.Core.Domain.PaymentStates", b =>
                {
                    b.HasOne("Pod.Core.Domain.PaymentRequest", "PaymentRequest")
                        .WithMany()
                        .HasForeignKey("PaymentRequestRequestId");

                    b.Navigation("PaymentRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
